# .github/workflows/lighthouse-ci.yml
name: 🏁 Shopify Lighthouse CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Lighthouse CI audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme code
        uses: actions/checkout@v4

      - name: Run Shopify Lighthouse CI
        uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_PASSWORD }}        # nếu dev store có password
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          lhci_min_score_performance: 0.9
          lhci_min_score_accessibility: 0.9
